# Generated by Django 2.2.1 on 2019-05-27 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobslistingpage',
            options={'verbose_name': 'Jobs Listing Page', 'verbose_name_plural': 'Jobs Listing Pages'},
        ),
    ]
