# Generated by Django 2.2.1 on 2019-05-29 15:22

from django.db import migrations, models
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190527_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True))])), ('subtitle', wagtail.core.blocks.StructBlock([('subtitle', wagtail.core.blocks.CharBlock(required=True))])), ('text', streams.blocks.SimpleRichTextBlock()), ('quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(required=True))])), ('video', wagtail.core.blocks.StructBlock([('youtube_video_id', wagtail.core.blocks.CharBlock(help_text='What goes after the "v=" in the url. Ex.: d9_DByee4FE ', required=True))])), ('fw_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Suggested width 1920px', required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('text_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Suggested width 1200px', required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('title_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Suggested width 1200px', required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('project', wagtail.core.blocks.StructBlock([('project', wagtail.core.blocks.PageChooserBlock(page_type=['behance.BehanceProjectPage'], required=True))]))], blank=True, null=True),
        ),
    ]
