# Generated by Django 2.2.1 on 2019-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='is_use_case',
            field=models.BooleanField(default=False),
        ),
    ]
