# Generated by Django 2.2.1 on 2019-05-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_is_use_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
