# Generated by Django 2.2.1 on 2019-05-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='likes',
            field=models.PositiveIntegerField(default=940),
        ),
    ]
