# Generated by Django 2.2.1 on 2019-05-29 18:17

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('blog', '0006_auto_20190529_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='employees',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='likes',
            field=models.PositiveIntegerField(default=1136),
        ),
    ]
