# Generated by Django 2.2.1 on 2019-05-29 19:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190529_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='likes',
            field=models.PositiveIntegerField(default=1473),
        ),
        migrations.CreateModel(
            name='BlogPageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('target', models.CharField(choices=[('_self', 'Same window'), ('_blank', 'New window')], default='_self', max_length=6)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='blog.BlogPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
