# Generated by Django 2.2.1 on 2019-05-27 18:53

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehanceProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('behance_id', models.PositiveIntegerField(editable=False)),
                ('behance_name', models.CharField(editable=False, max_length=255)),
                ('behance_url', models.URLField(blank=True, editable=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from='name')),
            ],
            options={
                'verbose_name': 'Behance Project',
                'verbose_name_plural': 'Behance Projects',
            },
        ),
        migrations.CreateModel(
            name='BehanceProjectListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Behance Projects Listing Page',
                'verbose_name_plural': 'Behance Projects Listing Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BehanceProjectModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Behance Project Module',
                'verbose_name_plural': 'Behance Project Modules',
            },
        ),
    ]
