# Generated by Django 2.2.1 on 2019-05-29 17:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
    ]
