# Generated by Django 2.2.1 on 2019-05-29 18:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock())])), ('three_pages', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Publicaciones destacadas', required=True)), ('page1', wagtail.core.blocks.PageChooserBlock(label='Pagina 0001')), ('page2', wagtail.core.blocks.PageChooserBlock()), ('page3', wagtail.core.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
    ]
