# Generated by Django 2.2.1 on 2019-05-29 18:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190529_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.StructBlock([('page', wagtail.core.blocks.PageChooserBlock())])), ('three_pages', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(default='Publicaciones destacadas')), ('page1', wagtail.core.blocks.PageChooserBlock()), ('page2', wagtail.core.blocks.PageChooserBlock()), ('page3', wagtail.core.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
    ]
