# Generated by Django 2.2.1 on 2019-06-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenciaegosettings',
            name='behance',
            field=models.URLField(blank=True, help_text='Behance URL', null=True),
        ),
    ]
