# Generated by Django 2.2.1 on 2019-06-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_agenciaegosettings_behance'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenciaegosettings',
            name='google_tagmanager_id',
            field=models.CharField(blank=True, help_text='Google TagManager ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agenciaegosettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics ID', max_length=100, null=True),
        ),
    ]
